apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-enforce-ip-range
  labels:
    app: webhook-enforce-ip-range
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-enforce-ip-range
  template:
    metadata:
      labels:
        app: webhook-enforce-ip-range
    spec:
      serviceAccountName: webhook-enforce-ip-range
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      containers:
        - name: webhook-enforce-ip-range-server
          image: kevinygu/capstone-webhook:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: metrics
            - containerPort: 8443
              name: tls
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/webhook/certs/
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
          resources:
             limits:
              memory: 128Mi
              cpu: 500m
      volumes:
        - name: tls-certs
          secret:
            secretName: webhook-tls
        - name: webhook-config
          configMap:
            name: webhook-enforce-ip-range-cm
