kind: Namespace
apiVersion: v1
metadata:
  name: tenant-a
  labels:
    sidecar-injector: "enabled"
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-a-1"]'
    cidr-range: '10.1.0.0/24'
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-a
  namespace: tenant-a
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
  restartPolicy: Always
