kind: Namespace
apiVersion: v1
metadata:
  name: tenant-b
  labels:
    sidecar-injector: "enabled"
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-b-1"]'
    cidr-range: '10.2.0.0/24'
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-b
  namespace: tenant-b
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
  restartPolicy: Always
