kind: Namespace
apiVersion: v1
metadata:
  name: tenant-a
  labels:
    sidecar-injector: "enabled"
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-a-1"]'
    cidr-range: '10.1.0.0/24'
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-a
  namespace: tenant-a
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
  restartPolicy: Always
