---
kind: Namespace
apiVersion: v1
metadata:
  name: tenant-a
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-a-1"]'
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-a
  namespace: tenant-a
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
  restartPolicy: Always
