---
kind: Namespace
apiVersion: v1
metadata:
  name: tenant-b
  annotations:
    cni.projectcalico.org/ipv4pools: '["pool-b-1"]'
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-b
  namespace: tenant-b
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
  restartPolicy: Always
